GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "Not working",
  "author": "Kevin Silva",
  "url": "https://github.com/kevinsilva",
  "likes": 0
  }

