# fly.toml app configuration file generated for fragrant-leaf-1030 on 2023-08-25T18:29:26+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fragrant-leaf-1030"
primary_region = "mad"

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
